import type { SupplierStatus } from './types';

export const supplierLabels = {
  agencyTitle: '공급기업 풀',
  agencyDesc: '발주 사업에 참여할 수 있는 공급기업의 전문 역량, 평가 이력, 내부 관리 태그를 관리합니다.',
  supplierTitle: '거래처 관리',
  supplierDesc: '당사가 거래하는 발주처와 수행 사업, 연장 가능성을 관리합니다.',
  addAgency: '공급기업 등록',
  addSupplier: '거래처 등록',
  total: '등록 공급기업',
  preferred: '우수 협력사',
  watch: '주의 관리',
  avgScore: '평균 평가점수',
  capabilityTitle: '구성 요약',
  capabilityDesc: '계약/수행 화면은 사업 진행을 보고, 이 화면은 업체별 역량과 평가 기록을 보는 곳입니다.',
  riskTitle: '관리 태그',
  riskDesc: '우수, 주의, 검토중 태그로 제안 요청이나 우선협상 때 참고합니다.',
  supplierName: '공급기업',
  clientName: '거래처/발주처',
  specialty: '전문 영역',
  contact: '대표 담당자',
  grade: '내부 등급',
  proposalCount: '참여 제안',
  winRate: '선정률',
  evaluation: '최근 평가',
  tags: '관리 태그',
  status: '상태',
  searchAgency: '공급기업명, 전문 영역, 태그 검색',
  searchSupplier: '거래처명, 분야, 담당자 검색',
  allSpecialty: '전문 영역 전체',
  allStatus: '상태 전체',
  count: '개사',
  cases: '건',
  point: '점',
  percent: '%',
  statusPreferred: '우수',
  statusActive: '운영중',
  statusReview: '검토중',
  statusWatch: '주의',
  detailTitle: '상세 정보',
  projectHistory: '참여/수행 사업',
  contactInfo: '담당자/연락',
  evaluationMemo: '평가 메모'
};

export const supplierFormLabels = {
  createTitle: '공급기업 등록',
  editTitle: '공급기업 수정',
  description: '발주 사업에 참여할 수 있는 공급기업의 기본 정보, 담당자, 수행 역량을 관리합니다.',
  basicInfo: '기본 정보',
  contactInfo: '담당자 정보',
  capabilityInfo: '기술 역량',
  companyName: '공급기업명',
  businessNumber: '사업자등록번호',
  companyType: '기업 유형',
  representative: '대표자',
  homepage: '홈페이지',
  address: '주소',
  contactName: '담당자명',
  contactDepartment: '소속/직책',
  contactEmail: '담당자 이메일',
  contactPhone: '담당자 연락처',
  coreTechnologies: '핵심 보유 기술',
  coreTechnologiesDesc: '업체가 보유한 주요 기술 스택이나 핵심 역량을 입력하세요.',
  certifications: '인증 및 등급 현황',
  certificationFile: '인증서 사본 업로드',
  grade: '내부 등급',
  status: '관리 상태',
  tags: '관리 태그',
  memo: '평가 메모',
  cancel: '취소',
  saveDraft: '임시 저장',
  create: '등록',
  update: '수정',
  saving: '저장 중...',
  addTechnology: '+ 추가',
  uploadSelected: '개 파일 선택됨',
  uploadEmpty: '클릭해서 인증서 파일을 선택하세요',
  uploadHelp: 'PDF, JPG, PNG (최대 10MB)',
  errorFallback: '공급기업 등록 중 오류가 발생했습니다.'
};

export const certificationOptions = [
  { title: 'GS 인증 (1등급)', description: 'Good Software' },
  { title: 'CMMI (Level 3+)', description: 'Process Capability' },
  { title: 'ISO 27001', description: 'Security Management' }
];

export const supplierStatusLabel: Record<SupplierStatus, string> = {
  preferred: supplierLabels.statusPreferred,
  active: supplierLabels.statusActive,
  review: supplierLabels.statusReview,
  watch: supplierLabels.statusWatch
};
